nidm/nidm-experiment/terms/MR-datasets/mr-datasets.owl
First version made at the Washington Task force meeting.
=> MR datasets ontology by @khelm and @drjturner

nidm/nidm-results/test/CheckConsistency.py, nidm/nidm-results/test/TestResultDataModel.py
This pull request includes a couple of fixes to the testing procedure of [NIDM-Results SPM exporter](https://github.com/incf-nidash/nidm-results_spm):
- take into account owl imports (for STATO terms),
- better reconciliation across graphs.
=> Fix for testing of NIDM-Results SPM exporter

nidm/nidm-results/scripts/UpdateExampleReadmes.py, nidm/nidm-results/scripts/UpdateTermReadme.py, nidm/nidm-results/scripts/recompute_all_ex.py, scripts/refresh.py
This pull request creates a new script `refresh.py` that can be called in order to:
- Update all examples in provn/ttl (based on template files) and upload them to the ProvStore.
- Update the specifications (based on owl files)
- Update the term README (based on owl files)
`refresh.py` can be called before sending a pull request to make sure that everything is up to date.
=> New script: refresh examples, readmes and specs

nidm/nidm-results/spm/example004/spm_inference_activities.provn, nidm/nidm-results/spm/example004/spm_inference_activities.ttl, nidm/nidm-results/terms/README.md, nidm/nidm-results/terms/nidm-results.owl
This pull request implement updates suggested at #294 and is open as a separate pull request so that discussions can be carried on at #294.
=> Definition of spm:"KConjunctionInference" -> spm:"PartialConjunctionInference"

doc/content/specs/nidm-results_dev.html, nidm/nidm-results/terms/README.md, nidm/nidm-results/terms/nidm-results.owl
This pull request implement updates suggested at #290 (up to https://github.com/incf-nidash/nidm/issues/290#issuecomment-92833826) and is open as a separate pull request so that discussions can be carried on at #290.
=> Definition of "Coordinate Space" (pending final vetting)

doc/content/specs/nidm-results_dev.html, nidm/nidm-results/fsl/README.md, nidm/nidm-results/fsl/example001/README.md, nidm/nidm-results/fsl/example001/fsl_nidm.provn, nidm/nidm-results/fsl/example001/fsl_nidm.ttl, nidm/nidm-results/fsl/fsl_results.provn, nidm/nidm-results/fsl/fsl_results.ttl, nidm/nidm-results/scripts/create_fsl_example.py, nidm/nidm-results/scripts/create_fsl_example_001.py, nidm/nidm-results/scripts/create_spm_example.py, nidm/nidm-results/scripts/create_spm_example_001.py, nidm/nidm-results/scripts/create_spm_example_002.py, nidm/nidm-results/scripts/create_spm_example_003.py, nidm/nidm-results/spm/README.md, nidm/nidm-results/spm/example001/README.md, nidm/nidm-results/spm/example001/example001_spm_results.provn, nidm/nidm-results/spm/example001/example001_spm_results.ttl, nidm/nidm-results/spm/example002/README.md, nidm/nidm-results/spm/example002/spm_results_2contrasts.provn, nidm/nidm-results/spm/example002/spm_results_2contrasts.ttl, nidm/nidm-results/spm/example003/README.md, nidm/nidm-results/spm/example003/spm_results_conjunction.provn, nidm/nidm-results/spm/example003/spm_results_conjunction.ttl, nidm/nidm-results/spm/spm_results.provn, nidm/nidm-results/spm/spm_results.ttl, nidm/nidm-results/terms/README.md, nidm/nidm-results/terms/nidm-results.owl, nidm/nidm-results/terms/templates/NIDMBundle.txt
**Terms**: `nidm:objectModel`, `nidm:NIDMObjectModel`, `nidm:FSLResults`, `nidm:SPMResults`
**Definition**: No definition yet...
This issue is open to discuss the definition of `objectModel` (attribute), `NIDMObjectModel` (range taken by `objectModel`) and `SPMResults` / `FSLResults` (sub-classes of `NIDMObjectModel`).
Example of use:
```
entity(niiri:spm_results_id,
[prov:type = 'prov:Bundle',
prov:label = "SPM Results",
nidm:objectModel = 'nidm:SPMResults',
nidm:version = "0.1.0"])
```
I am not sure about the naming of these terms. In particular, what is intended by "NIDM object models"? Are those the same as "NIDM components"? @satra I thought you might want to comment on this...
Any suggestion on the definitions or the naming is greatly appreciated.
=> Definition of  "objectModel"

nidm/nidm-results/test/TestResultDataModel.py
Now that we are dealing with several versions of NIDM-Results, this PR updates the test procedure so that it automatically checks which version is in use in the test data (looking at the `softwareVersion` attribute in the bundle) and compare with the corresponding tag (e.g. for "1.0.0", compare with https://github.com/incf-nidash/nidm/tree/NIDM-Results_1.0.0).
=> NIDM-Results tests: compare against a given version of nidm-results

nidm/nidm-experiment/terms/nidm-experiment.owl
Removed BaselineProtocol since we have PerformedPlan and SpecifiedPlan.  Added ImagingProtocol. Other cleanup.
=> update terms file

doc/content/specs/nidm-experiment_dev.html, nidm/nidm-experiment/terms/nidm-experiment.owl
Added `nidm:Modality` and removed modality-specific terms.
=> issue 434 add modality

nidm/nidm-experiment/terms/catalog-v001.xml
=> fixed path

README.md, doc/content/specs/nidm-results_dev.html
Following renaming of the repository in `nidm-specs` (previously `nidm`) by @satra.
=> Update link to build status in README

doc/content/specs/README.md, doc/content/specs/nidm-experiment_dev.html, nidm/nidm-experiment/imports/pato_import.ttl, nidm/nidm-experiment/imports/sio_import.ttl, nidm/nidm-experiment/terms/catalog-v001.xml, nidm/nidm-experiment/terms/nidm-experiment.owl
This PR adds terms used in the pynidm constants.py file.
=> Add constants terms

.gitignore, doc/content/pages/home.md, doc/content/specs/README.md, doc/fabfile.py, doc/pelicanconf.py
Updated packages and modified fabfile.py and pelicanconf.py files to reflect new package requirements so that web pages are now created.  See issue #461 for details.
=> fix webpage generation

doc/content/specs/include/nidm-experiment_head.html, doc/content/specs/nidm-experiment_dev.html
Added content to nidm-experiment specification document.
=> Update exp spec doc

nidm/nidm-experiment/imports/dicom_import.ttl, nidm/nidm-experiment/scripts/create_expe_specification.py, nidm/nidm-results/fsl/example001/fsl_nidm.json, nidm/nidm-results/fsl/fsl_results.json, nidm/nidm-results/spm/example001/example001_spm_results.json, nidm/nidm-results/spm/example002/spm_results_2contrasts.json, nidm/nidm-results/spm/example003/spm_results_conjunction.json, nidm/nidm-results/spm/spm_results.json, nidm/nidm-results/test/ground_truth/voxelwise_p050_fwe/nidm.json
added new dicom terms, extracted from DICOM documentation (and not DICOM tags) as children of existing NIDM terms.
=> updated dicom graph

doc/content/specs/nidm-experiment_dev.html, nidm/nidm-experiment/scripts/create_expe_specification.py, nidm/nidm-experiment/terms/README.md, nidm/nidm-experiment/terms/nidm-experiment.owl, nidm/nidm-results/fsl/example001/fsl_nidm.json, nidm/nidm-results/fsl/fsl_results.json, nidm/nidm-results/spm/example001/example001_spm_results.json, nidm/nidm-results/spm/example002/spm_results_2contrasts.json, nidm/nidm-results/spm/example003/spm_results_conjunction.json, nidm/nidm-results/spm/spm_results.json, nidm/nidm-results/test/ground_truth/f_test/nidm.json, nidm/nidm-results/test/ground_truth/voxelwise_p001_unc/nidm.json, nidm/nidm-results/test/ground_truth/voxelwise_p050_fwe/nidm.json, requirements.txt
Fixed issues with create_expe_specifications.py (no properties allowed)
=> updated exp specs

nidm/nidm-experiment/imports/bids_import.ttl, nidm/nidm-results/fsl/example001/fsl_nidm.json, nidm/nidm-results/fsl/fsl_results.json, nidm/nidm-results/spm/example001/example001_spm_results.json, nidm/nidm-results/spm/example002/spm_results_2contrasts.json, nidm/nidm-results/spm/example003/spm_results_conjunction.json, nidm/nidm-results/spm/spm_results.json, nidm/nidm-results/test/ground_truth/display_mask/nidm.json, nidm/nidm-results/test/ground_truth/voxelwise_p001_unc/nidm.json, nidm/nidm-results/test/ground_truth/voxelwise_p050_fwe/nidm.json
Added BIDS Entity names (not key names)
=> updated BIDS Entity names

nidm/nidm-experiment/imports/bids_import.ttl, nidm/nidm-results/fsl/example001/fsl_nidm.json, nidm/nidm-results/fsl/fsl_results.json, nidm/nidm-results/spm/example001/example001_spm_results.json, nidm/nidm-results/spm/example002/spm_results_2contrasts.json, nidm/nidm-results/spm/example003/spm_results_conjunction.json, nidm/nidm-results/spm/spm_results.json, nidm/nidm-results/test/ground_truth/display_mask/nidm.json, nidm/nidm-results/test/ground_truth/voxelwise_p001_unc/nidm.json, nidm/nidm-results/test/ground_truth/voxelwise_p050_fwe/nidm.json
Added all of the bids entities in Appendix IV: Entity table
=> added BIDS entities

doc/content/specs/nidm-experiment_dev.html, nidm/nidm-experiment/imports/sio_import.ttl, nidm/nidm-experiment/scripts/create_expe_specification.py, nidm/nidm-experiment/terms/README.md, nidm/nidm-experiment/terms/nidm-experiment.owl, nidm/nidm-results/fsl/example001/fsl_nidm.json, nidm/nidm-results/fsl/fsl_results.json, nidm/nidm-results/spm/example001/example001_spm_results.json, nidm/nidm-results/spm/example002/spm_results_2contrasts.json, nidm/nidm-results/spm/example003/spm_results_conjunction.json, nidm/nidm-results/spm/spm_results.json, nidm/nidm-results/test/ground_truth/f_test/nidm.json, nidm/nidm-results/test/ground_truth/voxelwise_p001_unc/nidm.json, nidm/nidm-results/test/ground_truth/voxelwise_p050_fwe/nidm.json
Added new terms needed for DISCOVERY project, made consistency corrections and corrected typos.
=> update 1 for discovery project

nidm/nidm-experiment/imports/obo_import.ttl, nidm/nidm-experiment/terms/catalog-v001.xml, nidm/nidm-experiment/terms/nidm-experiment.owl, nidm/nidm-results/fsl/example001/fsl_nidm.json, nidm/nidm-results/fsl/fsl_results.json, nidm/nidm-results/spm/example001/example001_spm_results.json, nidm/nidm-results/spm/example002/spm_results_2contrasts.json, nidm/nidm-results/spm/example003/spm_results_conjunction.json, nidm/nidm-results/spm/spm_results.json, nidm/nidm-results/test/ground_truth/display_mask/nidm.json, nidm/nidm-results/test/ground_truth/voxelwise_p001_unc/nidm.json, nidm/nidm-results/test/ground_truth/voxelwise_p050_fwe/nidm.json
put all of the obo terms in a single file to facilitate the creation of an obo dereferencing page.
=> consolidated obo files

README.md
Changed the README.md file to also include the link to the new NIDM-Experiment Expanded
=> Added Experiment Expanded to Readme
