incf-nidash/nidm-specs

doc/content/specs/nidm-experiment_dev.html
doc/content/specs/nidm-results_dev.html
nidm/nidm-results/scripts/create_results_specification.py
scripts/owl_to_webpage.py

This pull request introduces the following updates to the `NIDM-Results` specification:
- Divide the specification in 4 subsections: 
1. Description of generic entities used throughout the specification (e.g. `Map`)
2. Description of entities used around the first activity `nidm:ModelParametersEstimation`
3. Description of entities used around the second activity `nidm:ContrastEstimation`
4. Description of entities used around the third activity `nidm:Inference`
- When a class is used as range by an Object Property (e.g. `nidm:EstimationMethod` is the range for `nidm: withEstimationMethod `, include the description of this class just after the first use of the corresponding ObjectProperty.

NIDM-Results specification: re-organisation in 4 sub-sections

---

.gitignore
.travis.yml
nidm/nidm-results/test/TestCommons.py

In this pull request:
- we catch timeouts (>5s) on `urlopen` and `read` calls to the ProvStore (and Prov validator)
- retry the call on timeout (up to 15 times).
This fixes issue #254, though we will probably want to avoid calling the prov store in the future (and rather use the prov python toolbox). So I think #254 can remain open.

Retry on timeout when calling the ProvStore

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

**Term**: `ModelParametersEstimation`
**Definition**: "The process of estimating the parameters of a general linear model from the available data".
**Original comment**: [link](https://docs.google.com/spreadsheets/d/16pC2cDsdxlzv2CzlNMtStqt5-xHwDEsU6MjZVxWhrE4/edit?usp=sharing)
**Current link**:  [nidm-results.owl/ModelParametersEstimation](https://github.com/incf-nidash/nidm/blob/master/nidm/nidm-results/nidm-results.owl#L2162-L2177)
---
@cmaumet `11:46 25 Apr`
How about re-using the STATO definition: "model parameter estimation is a data transformation part of a regression analysis which applies specific mathematical transformation in order produced estimates on the parameter specified by the model based on the data used as input."
@cmaumet `12:11 8 May`
Awaiting STATO reply at …

Definition of "ModelParametersEstimation"

---

nidm/nidm-results/terms/nidm-results.owl
scripts/OwlReader.py

In `nidm-results.owl`, we use [rdfs:isDefinedBy](http://www.w3.org/TR/rdf-schema/#ch_isdefinedby) attribute to specify the definition while in `nidm-experiment.owl`, we use [IAO:"definition" (obo:IAO_0000115)](http://www.ontobee.org/browser/rdf.php?o=IAO&iri=http://purl.obolibrary.org/obo/IAO_0000115). The definition of the latter seems more appropriate but is directly linked with OBO while the former might be more generic. 
Do you know if there is a good practice?

Use of rdfs:isDefinedBy or iao:"definition" for definitions

---

nidm/nidm-results/terms/README.md
scripts/OwlReader.py

In this pull request, we:
- include a small update to consider a term as uncurated is its curation status is missing. 
- update the README file describing the terms accordingly ([current README](https://github.com/incf-nidash/nidm/blob/master/nidm/nidm-results/terms/README.md), [updated README](https://github.com/incf-nidash/nidm/blob/9169227acee06fc36995e53d342689708d72ad96/nidm/nidm-results/terms/README.md)).

Term README: consider term as uncurated if curation status is missing

---

nidm/nidm-results/scripts/UpdateTermReadme.py
nidm/nidm-results/terms/README.md

In this pull request, we:
- include a small fix to display a term even if its definition is missing. 
- update the README file describing the terms accordingly ([current README](https://github.com/incf-nidash/nidm/blob/master/nidm/nidm-results/terms/README.md), [updated README](https://github.com/cmaumet/nidm/blob/empty_definition_in_term_README/nidm/nidm-results/terms/README.md)).

fix: Display terms with empty definition in README

---

doc/content/specs/nidm-results_020.html
doc/content/specs/nidm-results_dev.html
nidm/nidm-results/scripts/create_results_specification.py
nidm/nidm-results/terms/nidm-results.owl
nidm/nidm-results/terms/releases/nidm-results_020.owl
scripts/OwlReader.py
scripts/owl_to_webpage.py

Specification: small fixes to be implemented

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

This issue is open to curate the definition of **nidm:ExtentThreshold**.
- *nidm:ExtentThreshold*: "A numerical value that establishes a bound on a range of cluster-sizes. / [from extentThresh:] Minimum cluster size used when thresholding a statistic image 5voxels"
A `nidm:ExtentThreshold` is used an an input of `nidm:Inference` (see also [ExtentThreshold in the spec](http://nidm.nidash.org/specs/nidm-results_dev.html#section-nidm:ExtentThreshold)). 
- E.g. of `nidm:ExtentThreshold` entity for a cluster-wise threshold of p<0.05:
```
niiri:extent_threshold_id a prov:Entity , nidm:ExtentThreshold ;
rdfs:label "Extent Threshold: p<0.05 (FWE)" ;
nidm:userSpecifiedThresholdType "p-value FWE"^^xsd:string ;
nidm:pValueFWER "0.05"^^xsd:float .
```
- E.g. of `nidm:ExtentThreshold` entity with a …

Definition of "ExtentThreshold" (metadata complete)

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

This issue is open to curate the definition of **nidm:clusterLabelId**.
- *nidm:clusterLabelId*: Integer associated with a particular cluster as specified in the clusterLabelsMap. 
`nidm:clusterLabelId` is an attribute in entities of type `nidm:SignificantCluster`, e.g.:
<pre>
niiri:significant_cluster_0002 a prov:Entity , nidm:SignificantCluster ;
rdfs:label "Significant Cluster: 0002" ;
<b>nidm:clusterLabelId "2"^^xsd:int ;</b>
...
prov:wasDerivedFrom niiri:excursion_set_map_id .
niiri:excursion_set_map_id a prov:Entity , nidm:ExcursionSetMap ;
rdfs:label "Excursion Set Map" ;
...
nidm:hasClusterLabelsMap niiri:cluster_label_map_id .
</pre>
-----
I wonder if something like:
- *nidm:clusterLabelId*: An integer value used in the cluster label map to identify the location of the cluster. …

Definition of `clusterLabelId` (pending final vetting)

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

This issue is open to discuss the definition of **nidm:MapHeader** and its associated object property **nidm:hasMapHeader**.
How about:
- **nidm:MapHeader**: Nifti header file (.hdr).
- **nidm:hasMapHeader**: Property that associates a map header with a map.
?
<pre>
niiri:contrast_map_id_der a prov:Entity , nidm:ContrastMap ;
nfo:fileName "con_0001.img"^^xsd:string ;
dct:format "image/nifti"^^xsd:string ;
<b>nidm:hasMapHeader niiri:original_contrast_map_header_id ;</b>
crypto:sha512 "e43b6e01b0463fe7d40782137867a..."^^xsd:string .
niiri:original_contrast_map_header_id a prov:Entity , <b>nidm:MapHeader</b> ;
dct:format "image/nifti"^^xsd:string ;
nfo:fileName "con_0001.hdr"^^xsd:string ;
crypto:sha512 "e43b6e01b0463fe7d40782137867a..."^^xsd:string .
</pre>

Definition of "MapHeader" (current status: uncurated)

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

This issue is open to curate the remaining uncurated attributes of *nidm:CoordinateSpace* (cf. [example of usage](http://nidm.nidash.org/specs/nidm-results_dev.html#dfn-nidm-coordinatespace) in the spec).
- **nidm:voxelUnits**: **set of** units associated with each dimensions of some N-dimensional data **(e.g. [mm, mm, mm])**.
- **nidm:voxelSize**: 3D size of a voxel measured in voxel units (e.g. [2, 2, 4]).
- **nidm:numberOfDimensions**: Number of dimensions of the data matrix (e.g. 3 for volumetric data)
- **nidm:voxelUnits**: Units associated with each dimensions of some N-dimensional data.
- **nidm:voxelSize**: 3D size of a voxel measured in voxelUnits.
- **nidm:numberOfDimensions**: Number of dimensions of a data matrix

Definition of voxelUnits, voxelSize and numberOfDimensions 

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

This issue is open to curate the definition of **nidm:HeightThreshold**.
- *nidm:HeightThreshold*: "A numerical value that establishes a bound on a range of voxelwise or vertex-wise defined statistic."
A `nidm:HeightThreshold` is used an an input of `nidm:Inference` (see also [example of usage of HeightThreshold in the spec](http://nidm.nidash.org/specs/nidm-results_dev.html#dfn-nidm-heightthreshold)). 
Similarly to what was recently agreed for *nidm:ExtentThreshold* (cf. #273), how about:
- *nidm:HeightThreshold*: **A numerical value that establishes a bound on a range of statistic values and can be specified by the user in terms of FWER-corrected p-value, uncorrected p-value or minimum statistic value.**
?

Definition of "HeightThreshold" (current status: pending final vetting)

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

This issue is open to curate the definition of **nidm:ClusterLabelsMap** and its corresponding object property **nidm:hasClusterLabelsMap**:
How about:
- **nidm:ClusterLabelsMap**: Map whose value at each location denotes cluster membership within the excursion set. Each cluster is denoted by a different integer.
- **nidm:hasClusterLabelsMap**: Property that associates a clusters label map to the excursion set.
?
Note:
- The proposed definition of *nidm:hasClusterLabelsMap* is similar to definitions used for other object properties (e.g. [nidm:hasConnectivityCriterion](http://nidm.nidash.org/specs/nidm-results_dev.html#dfn-nidm-hasconnectivitycriterion), [nidm:hasErrorDependence](http://nidm.nidash.org/specs/nidm-results_dev.html#dfn-nidm-haserrordependence))
- Adding "within the …

Definition of "ClusterLabelsMap" (current status: uncurated)

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/fsl/example001/fsl_nidm.provn
nidm/nidm-results/fsl/example001/fsl_nidm.ttl
nidm/nidm-results/fsl/fsl_results.provn
nidm/nidm-results/fsl/fsl_results.ttl
nidm/nidm-results/spm/example001/example001_spm_results.provn
nidm/nidm-results/spm/example001/example001_spm_results.ttl
nidm/nidm-results/spm/example002/spm_results_2contrasts.provn
nidm/nidm-results/spm/example002/spm_results_2contrasts.ttl
nidm/nidm-results/spm/example003/spm_results_conjunction.provn
nidm/nidm-results/spm/example003/spm_results_conjunction.ttl
nidm/nidm-results/spm/spm_results.provn
nidm/nidm-results/spm/spm_results.ttl
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/examples/ErrorModel.txt
nidm/nidm-results/terms/nidm-results.owl

This issue is a companion for #176 to define the terms created to model noise spatial models, namely:
- `nidm:varianceSpatialModel`
- `nidm:dependenceSpatialModel`
- `nidm:SpatialModel`
- `nidm:SpatiallyLocalModel`
- `nidm:SpatiallyGlobalModel`
- `nidm:SpatiallyRegularisedModel`
Proposed definitions:
- **nidm:SpatialModel**: "Spatial model of the Noise Model variance or dependence"
- **nidm:varianceSpatialModel**: "Property that associates a Spatial Model to the variance of a noise model".
- **nidm:dependenceSpatialModel**: "Property that associates a Spatial Model to the dependence of a noise model".
- **nidm:SpatiallyLocalModel**: "Model defined independently for each element".
- **nidm:SpatiallyGlobalModel**: "Model defined globally for all elements".
- …

Definition of "noise spatial model" terms

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/spm/example001/example001_spm_results.provn
nidm/nidm-results/spm/example001/example001_spm_results.ttl
nidm/nidm-results/spm/spm_results.provn
nidm/nidm-results/spm/spm_results.ttl
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/examples/ExcursionSetMap.txt
nidm/nidm-results/terms/nidm-results.owl

How do you feel about:
- **nidm:numberOfClusters**: number of significant clusters found by the inference activity. 
?
*nidm:numberOfClusters* is an attribute of a *nidm:ExcursionSetMap*, cf. [example of usage](http://nidm.nidash.org/specs/nidm-results_dev.html#dfn-nidm-excursionsetmap) in the spec.

Definition of "nidm:numberOfClusters" (current status: uncurated)

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

This issue is open to curate the definition of **nidm:GrandMeanMap** and its attributes.
Similarly to what we have done for other *Map* terms in #255, how about:
- **nidm:GrandMeanMap**: A map whose value at each element is the mean of the means (i.e. the grand mean) of the input data to the activity that generated this map.
Cf. [example of usage](http://nidm.nidash.org/specs/nidm-results_dev.html#dfn-nidm-grandmeanmap) in the specs.
@jbpoline, @nicholst: would you have suggestions to improve the definition of "grand mean"? Thank you!

Definition of "GrandMeanMap"

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/fsl/example001/fsl_nidm.provn
nidm/nidm-results/fsl/example001/fsl_nidm.ttl
nidm/nidm-results/fsl/fsl_results.provn
nidm/nidm-results/fsl/fsl_results.ttl
nidm/nidm-results/spm/example001/example001_spm_results.provn
nidm/nidm-results/spm/example001/example001_spm_results.ttl
nidm/nidm-results/spm/example002/spm_results_2contrasts.provn
nidm/nidm-results/spm/example002/spm_results_2contrasts.ttl
nidm/nidm-results/spm/example003/spm_results_conjunction.provn
nidm/nidm-results/spm/example003/spm_results_conjunction.ttl
nidm/nidm-results/spm/spm_results.provn
nidm/nidm-results/spm/spm_results.ttl
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/examples/Data.txt
nidm/nidm-results/terms/nidm-results.owl

This issue is open to curate **nidm:Data** and its attributes.
We created the *nidm:Data* class a while ago, as a placeholder for the input data and were planning to provide a more precise description in a future version. Since then we had a lot of discussions on the relationship between NIDM-Results and NIDM-Workflows (e.g. in #114 and [slides](https://docs.google.com/presentation/d/1W4l_xhxE4LpKkDhQouBVab0H-W1E-299wm50ZT-j4B0/edit?usp=sharing)) and I think now would be a good time to rethink about this entity. 
As the *nidm:Data* entity is only storing information about data scaling and not data itself (cf. [example of usage](http://nidm.nidash.org/specs/nidm-results_dev.html#dfn-nidm-data)), I would like to propose to rename it to *nidm:DataScaling* with the following definition:
- …

Definition of "nidm:DataScaling" (replacing "nidm:Data")

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

Following #248, this issue is open to discuss the definitions of the terms used to model the hemodynamic response function (HRF):
First, let's define the parent class and its associated object property:
- **nidm:HemodynamicResponseFunctionBasis**: A basis function, part of a set of functions that is convolved with the anticipated neural responses to obtain the anticipated hemodynamic responses. (adapted from the definition suggested by @jbpoline in #248).
- **nidm:hasHRFBasis**: Hemodynamic response function basis used to model the anticipated hemodynamic response.
Definitions for children of *nidm:HemodynamicResponseFunctionBasis*:
- **nidm:HemodynamicResponseFunction**: Hemodynamic response function basis that can on its own be used to represent the idealised hemodynamic response …

Definitions of HRF terms (current status: uncurated)

---

nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

Another definition, pending final vetting, that I think is good to go:
- **nidm:'cluster Size In Voxels'**: Number of voxels that make up the cluster.
What do you think?

Definition of 'cluster Size In Voxels' (pending final vetting)

---

nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

Following #261, this issue is open to curate the definition of the "Drift Model" terms (cf. [example of usage](http://htmlpreview.github.io/?https://raw.githubusercontent.com/incf-nidash/nidm/9cd873495390d9dcc8fb42697ddb9fe937fa6f23/doc/content/specs/nidm-results_dev.html#dfn-nidm-designmatrix) in the spec).
Classes:
- **nidm:DriftModel**: A model used to compensate for low frequency baseline drifts when analyzing functional MRI data at the subject level
- **afni:LegendrePolynomialDriftModel**: A drift model in which the drifts are modeled by a Legendre orthogonal polynomial basis added to the regression model
- **fsl:GaussianRunningLineDriftModel**: A drift model in which the drifts are modeled with a Gaussian-weighted running line smoother, fit to and subtracted from the data and each …

Definition of "Drift Model" terms

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

Following #52 and #123, this issue is open to curate the definitions of the terms used to model coordinate systems.
First, let's define the parent class and its associated object property:
- **nidm:WorldCoordinateSystem**: reference space on which real-world positions are expressed (cf. [Nifti-1 FAQ question 14](http://nifti.nimh.nih.gov/nifti-1/documentation/faq#Q14) and [Understanding affines on nipy](http://nipy.org/nipy/stable/devel/code_discussions/understanding_affines.html)
). A world coordinate system can be represented by an image obtained by registering an initial set of images, using a given normalization algorithm to match a target template.
- **nidm:inWorldCoordinateSystem**: Property that associates a world coordinate system to the coordinate space.
Terms *in italics* are …

Definition of "coordinate system" terms

---

doc/content/specs/nidm-results_dev.html
nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

I propose the following actions
* **nidm:DesignMatrix** :  Replace with external term "design matrix" http://purl.obolibrary.org/obo/STATO_0000289 (in fact proposed by Nolan!)
* **nidm:ZStatistic** : This term can be deleted.  (SPM & FSL have nidm:equivalentZStatistic on the results page).  The term "z-score" can also be directly references: http://purl.obolibrary.org/obo/STATO_0000104 
Current definitions: 
* **nidm:DesignMatrix** :  A matrix of values defining the explanatory variables used in a regression model. Each column corresponds to one explanatory variable, each row corresponds to one observation 
* **nidm:ZStatistic** : *undefined* 
@jbpoline , @cmaumet: Comments?
(See PURL links for STATO definitions)

Further STATO reuse: Design Matrix and Z statistic

---

nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

Following discussions with @cmaumet, motivated by development of the FSL results model, we realised that our term definitions for noise spatial smoothness (aka FWHM) were a bit ropey.  This issue proposes some revisions to the SPM smoothness terms *and* proposes some new terms for the FSL parameters.
The present terms `spm:noiseFWHMInUnits`, `spm:noiseFWHMInVertices` and `spm:noiseFWHMInVoxels` are ambiguous because they make no mention of *space*, and as such one could take FHWM to be a description of the univariate noise variance!  
Current descriptions, as pulled from [terms README](https://github.com/incf-nidash/nidm/blob/master/nidm/nidm-results/terms/README.md): 
* **spm:noiseFWHMInUnits**: Estimated Full Width at Half Maximum of the noise distribution in world units.
* …

Refining the definition of FWHM, and defining FSL's equivalent measure

---

nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

**Term**: `noiseFWHM `
**Current definition**: "Estimated Full Width at Half Maximum of the noise distribution."
**See also**: [Full_Width_at_Half_Maximum](http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Full_Width_at_Half_Maximum)
---
@Jessica Turner `03:44 5 Mar 2013`
[Commenting on "see also: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Full_Width_at_Half_Maximum"]
this is the definition of FWHM, not the FWHM of the noise, per se
@cmaumet `08:41 24 Apr`
Would it be better to have the NCICB FWHM term as a parent of noiseFWHM?
@nicholsn `22:02 24 Apr`
noiseFWHM seems more like an attribute of some entity whose FWHM was calculated. Child terms should stand in an "is-a" relationship with parent terms. Following this which would you choose?
noiseFWHM is-a noiseMeasure
or
noiseFWHM …

noiseFWHM: see also "Full width at half maximum"

---

nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

This issue is open to discuss the terms used for k-conjunction inference.
Similarly to the definition of *nidm:ConjunctionInference* (cf. #134), what do you think of:
- **spm:KConjunctionInference**: the process of testing for the joint significance of multiple effects, with emphasis on rejecting one or more (instead of all) of the respective null hypotheses as defined by the global null degree attribute. This process is also known as "global null conjunction" in SPM.
- **nidm:globalNullDegree**: number of null hypothesis to be rejected in a k-conjunction inference.
?
I am happy to keep *KConjunctionInference* in the SPM namespace as I believe this type of conjunction is specific to SPM (but no strong feeling on this). But I think that if we keep *KConjunctionInference* in the `spm` …

Definition of "k-conjunction inference" terms

---

nidm/nidm-results/terms/README.md
nidm/nidm-results/terms/nidm-results.owl

**Original term**: `nonStationaryRandomField`
**Original definition**: "Random field that is variable across the search volume".
**Original comment**: [link](https://docs.google.com/spreadsheets/d/16pC2cDsdxlzv2CzlNMtStqt5-xHwDEsU6MjZVxWhrE4/edit?disco=AAAAAJVbYzE)
**Current term**: `randomFieldStationarity`
**Current link**:  [nidm-results.owl/nonStationaryRandomField](https://github.com/incf-nidash/nidm/blob/master/nidm/nidm-results/nidm-results.owl#L619-L632)
**Current definition**: "Is the random field assumed to be stationary across the entire search volume?" 
---
@cmaumet `10:44 9 Apr`
This also needs to be reviewed.
@khelm `19:39 23 Apr`
Yes, I agree. How about "A stochastic process that is indexed by a spatial variable in which the process has a mean, variance or covariance that …

Definition of "randomFieldStationarity"

---

doc/content/specs/nidm-results_100.html
doc/content/specs/nidm-results_dev.html
nidm/imports/iao_import.ttl
nidm/imports/stato_import.ttl
nidm/nidm-results/scripts/release_nidm_results.py
nidm/nidm-results/terms/nidm-results.owl
nidm/nidm-results/terms/releases/nidm-results_100.owl
scripts/Constants.py
scripts/OwlReader.py
test/test_specifications.py
vcr_cassettes/synopsis.yaml

The pull request introduces a new script `nidm/nidm-results/scripts/release_nidm_results.py` which can be used to generate an owl file for release. The script perform the following steps:
- Copy the current owl file (in `nidm-results/terms/`) to the `release` folder.
- Remove the imports commands and copy the imported triples directly in the release file.
- Update the examples addresses (i.e. replace `https://raw.githubusercontent.com/incf-nidash/nidm/master/` by `https://raw.githubusercontent.com/incf-nidash/nidm/NIDM-Results_x.x.x`
- For a release version older (or equal to) 1.0.0, remove AFNI-related terms (not yet ready for release).
The script can be called as follows (replace "1.0.0" with the appropriate version number):
```
python nidm/nidm-results/scripts/release_nidm_results.py …
```

New script: create a NIDM-Results release

---

doc/content/specs/nidm-results.html

This is a small fix that should have been implemented as part of https://github.com/incf-nidash/nidm/pull/334.

nidm-results.html redirects to 1.1.0 spec

---

index.html

I fixed a typo in the nidash-homepage.
"that define extensions the the" to "that define extensions to the"

fixed typo in homepage

---

nidm/nidm-experiment/ncanda/check_cube_for_duplicate_obs.rq
nidm/nidm-experiment/ncanda/fs-cube.ttl
nidm/nidm-experiment/ncanda/ncanda-event-hemi-region-thick.rq
nidm/nidm-experiment/ncanda/ncanda-measures-name-datatype.rq

This PR adds an example [RDF Data Cube][1] to nidm experiment for discussion on the monday call. This model is based off of the freesurfer example and includes additional information that would be appropriate for a data dictionary/common data element model. I've also included some preliminary mappings to PROV.
A complete example includes the following corresponding information:
[1]:  http://www.w3.org/TR/vocab-data-cube/

WIP: Example freesurfer data cube

---

nidm/nidm-experiment/terms/nidm-experiment.owl
vcr_cassettes/synopsis.yaml

Use explicitely the "nidm" prefix (rather than a default namespace on ":") for the experiment model.

Explicitely use "nidm" prefix in nidm-experiment.owl

---

doc/content/specs/include/nidm-experiment_head.html
doc/content/specs/include/nidm-results_dev_head.html
doc/content/specs/include/nidm-results_head.html
doc/content/specs/nidm-descriptor.html
doc/content/specs/nidm-experiment_dev.html
doc/content/specs/nidm-overview.html
doc/content/specs/nidm-primer.html
doc/content/specs/nidm-results_010.html
doc/content/specs/nidm-results_020.html
doc/content/specs/nidm-results_100.html
doc/content/specs/nidm-results_110.html
doc/content/specs/nidm-results_120.html
doc/content/specs/nidm-results_130-rc1.html
doc/content/specs/nidm-results_130-rc2.html
doc/content/specs/nidm-results_130-rc3.html
doc/content/specs/nidm-results_130.html
doc/content/specs/nidm-results_dev.html

Following discussions by email that led to the creation of a public mailing list to gather feedback from NIDM users (https://groups.google.com/forum/#!forum/nidm-users), this pull request updates the documentation to mention the mailing list address.

Link to public mailing list for comments

---

.travis.yml

As in https://github.com/incf-nidash/nidmresults-spm/pull/33, this pull request add an update of the setuptools package before install of the requirements to avoid the `html5lib requires setuptools version 18.5 or above; please upgrade before installing (you have 12.0.5)` error.

Fix install error

---

doc/content/pages/home.md
doc/content/specs/include/nidm-experiment_head.html
doc/content/specs/include/nidm-results_head.html
doc/content/specs/nidm-descriptor.html
doc/content/specs/nidm-experiment_dev.html
doc/content/specs/nidm-overview.html
doc/content/specs/nidm-primer.html
doc/content/specs/nidm-results_100.html
doc/content/specs/nidm-results_110.html
doc/content/specs/nidm-results_120.html
doc/content/specs/nidm-results_130-rc1.html
doc/content/specs/nidm-results_130-rc2.html
doc/content/specs/nidm-results_130-rc3.html
doc/content/specs/nidm-results_130.html
doc/content/specs/nidm-spec-template.html
nidm/container/cff.provn
nidm/nidm-dataset-descriptors/nidm-desc-sum-database-level.ttl
nidm/nidm-dataset-descriptors/nidm.ttl
nidm/nidm-results/scripts/NIDM-Results-Terms2RDF.ipynb
nidm/nidm-results/scripts/NIDM_Results_queries.ipynb

This pull requests fix a number of typos in the specification documents:
- Broken link to NIDM-Results specification in NIDM-primer (reported by @TomMaullin)
- "the the" typo reported in #376
- URL of the `nidm` namespace had not been updated to purl in the HTML specs (and was therefore inconsistent with the `owl` file).

Fix typos in the online specifications

---

nidm/nidm-results/scripts/create_spm_example_001.py
nidm/nidm-results/spm/example001/example001_spm_results.ttl

This PR includes a few fixes in the NIDM-Results SPM examples, in particular:
- Create separate entities for derived parameter estimate maps (now considering that the beta maps are exported and included in the NIDM-Results pack).
- Update the placeholder sha-sum to the actual values.
Those fixes were created as part of the test of the updated SPM exporter at: https://github.com/incf-nidash/nidmresults-spm/pull/36.

Small fixes in NIDM-Results 1.3.0 examples: cluster label map in SPM, beta exported

---

doc/content/specs/nidm-experiment_dev.html
doc/content/specs/nidm-results_dev.html
nidm/nidm-experiment/imports/sio_import.ttl
nidm/nidm-experiment/terms/nidm-experiment.owl

This PR:
Done - 15) Should we create the more generic "Protocol" as a Performed Plan and then tag using nidm:AcquisitionModality? Answer = yes.
3) score should go under mathematical_entity
4) what is a scale_item?
There are all types of scales in SIO - decimal scale, integer scale, etc. Do we need any of these?
The issue here is that both can be either a sio:'language entity' or a sio:'mathematical entity', so I have
to make the parent more general than each (except now onl:scale_item and onl:score are on the same level as both of those entities which seems not quite right since score and scale_item has an "is a" relationship with those entities. This will have to be revisited later as a separate issue.
Done 2) The definition of onl:scale is consistent with it being a sio:"language …

Issue cleanup

---

doc/fabfile.py

Fixed built with @khelm at the Montreal neuroinformatics hackathon. 
Fixes the webpage generation. 
This updates the arguments to the serve function to add an optional argument specifying the full path to the pelican command. The fix setting the conda environement using a full path (proposed in #467) was causing an internal conda error on @khelm's machine (KeyError 'PATH').

website: Set path to pelican as optional argument

---

doc/content/specs/nidm-experiment_dev.html
scripts/owl_to_webpage.py

Code was writing the prefix of "neuro:" for all of the ontoneurolog-instruments term.  This was assigned in `.../scripts/owl_to_webpage.py`. Changed this to "onli" which is being used in the nidm-experiment.owl file and in PyNIDM.

fixed neuro->onli prefix

---

doc/content/specs/nidm_html/dicom.html
doc/content/specs/nidm_html/obo.html
doc/content/specs/nidm_html/sio.html
nidm/nidm-results/fsl/example001/fsl_nidm.json
nidm/nidm-results/scripts/create_example_from_templates.py
nidm/nidm-results/spm/example001/example001_spm_results.json
nidm/nidm-results/spm/example002/spm_results_2contrasts.json
nidm/nidm-results/spm/example003/spm_results_conjunction.json
nidm/nidm-results/spm/spm_results.json
nidm/nidm-results/test/ground_truth/display_mask/nidm.json
nidm/nidm-results/test/ground_truth/event_related_design/nidm.json
nidm/nidm-results/test/ground_truth/explicit_mask/nidm.json
nidm/nidm-results/test/ground_truth/f_test/nidm.json
nidm/nidm-results/test/ground_truth/voxelwise_p001_unc/nidm.json
nidm/nidm-results/test/ground_truth/voxelwise_p050_fwe/nidm.json
scripts/refresh.py

Issue is with trying to reach the nidm-results context file 
https://raw.githubusercontent.com/incf-nidash/nidm/master/nidm/nidm-results/terms/nidmr.json
with purl redirect:
http://purl.org/nidash/context
error message discuss in [issue 148](https://github.com/incf-nidash/nidm-specs/issues/418)
Problem can't be solved without upgrading urllib3/requests to versions past what's installed with nidmresults package.
To resolve, I commented out two lines in refresh.py that called the json-ld context file.

comment out context file use in refresh.py
